# Object Oriented Programming
---

We've been writing code in somewhat of a 'functional' style --- that is we've been writing separate functions that each accomplish one particular task and are isolated from each other. This is a perfectly valid way of writing code, and has pros and cons just like any other style of progoramming. What we'll explore next is a style of programming called Object Oriented Programming (OOP). OOP is a programming paradigm that gives us the ability to think about and structure our code as a real-world object. So instead of passing arrays between functions, we'll create a 'Game of Life board' object with persistent data and we'll use that for our simulation (BAD). This style of programming also has pros and cons. We won't get into those here, I think that the best way to learn about which programming paradigm you should choose to use for a given task is through experience. 

## Administrivia

In [6]:
import numpy as np

## A Quick Introduction to Classes

In [ ]:
# Simplest possible class
class MyClass:
    attribute = 'This is an attribute!'
    
MyClass.attribute

In [ ]:
# A bit more complicated
class MyClass:
    def __init__(self, attribute):
        self.attribute = attribute
        
instance = MyClass('This is an instance attribute')
instance.attribute

## Game of Life Class

Let's start by thinking about the properties that our Game of Life object should have and the sorts of actions it should be able to perform.

* It should be able to start a simulation with a new 'board'
* It should be able to step forward through generations
* We may want to start a new simulation if all of the cells in the board are dead, so we should write a function to query the board to see if all the cells are dead

In [1]:
# Skeleton Class
class GameOfLife:
    """Conway's Game of Life"""
    def __init__(self):
        """Initialize a class instance"""
        pass

    def start(self):
        """Start a new simulation."""
        pass
    
    def step(self):
        """Step the simulation forward a generation."""
        pass
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def restart(self):
        """Restart the Game of Life simulation with a new board"""
        pass

Now let's start filling this class in.

We'll start with our initialization method. We don't have a simulation running yet, but we want a 'board' attribute to be accessible to the other functions in the class, so we'll go ahead and add an empty board.

In [2]:
class GameOfLife:
    """Conway's Game of Life"""
    def __init__(self):
        """Initialize a class instance"""
        self.board = None

    def start(self):
        """Start a new simulation."""
        pass
    
    def step(self):
        """Step the simulation forward a generation."""
        pass
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def restart(self):
        """Restart the Game of Life simulation with a new board"""
        pass

In [3]:
simulation = GameOfLife()
print(simulation.board)

None


Next we'll write the start method. This should create a new game board of a given size. We'll rip off the `create_board` function that we wrote earlier, rename it as `new_board`, which makes more sense in this context, and call that function under our class's start method.

In [4]:
class GameOfLife:
    DEAD, ALIVE = 0, 1 # These are Class variables
    """Conway's Game of Life"""
    def __init__(self):
        """Initialize a class instance"""
        self.board = None

    def start(self, height, width, p_alive=.3):
        """Start a new simulation."""
        self.new_board(height, width, p_alive)
    
    def step(self):
        """Step the simulation forward a generation."""
        pass
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def new_board(self, height, width, p_alive):
        """
        This function creates a Game of Life game board.

        Parameters
        ----------
            height : integer
                the height of the board
            width : integer
                the width of the board
            p_alive : float
                the chance that a cell is set to 'alive', must be between [0, 1]
                
        """
        p_dead = 1 - p_alive # We know that if a cell is not alive, it must be dead
        self.board = np.random.choice(
            [self.DEAD, self.ALIVE], p=[p_dead, p_alive], size=(height, width)
        )
    
    def restart(self):
        """Restart the Game of Life simulation with a new board"""
        pass

In [7]:
simulation = GameOfLife()
simulation.start(height=10, width=10)
simulation.board

array([[0, 1, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0]])

Next, let's add in the functionality to step to the next generation.

In [9]:
class GameOfLife:
    """Conway's Game of Life"""
    DEAD, ALIVE = 0, 1
    def __init__(self):
        """Initialize a class instance"""
        self.board = None

    def start(self, height, width, p_alive=.3):
        """Start a new simulation."""
        self.new_board(height, width, p_alive)
    
    def step(self):
        """Step the simulation forward a generation."""
        # Copy the current board for the next generation
        next_board = self.board.copy()
        # Loop over all of the cells in the current board
        num_rows, num_cols = self.board.shape
        for r in range(num_rows):
            for c in range(num_cols):
                # Fetch the current state of this cell
                current_state = self.board[r, c]
                # Count the number of living neighbors
                num_living_neighbors = self.count_living_neighbors(r, c)
                # Figure out if this cell will be alive or dead in the next board
                next_state = self.compute_next_state(current_state, num_living_neighbors)
    #             next_state = 1
                # Set the state of this cell in the next board
                next_board[r, c] = next_state  

        self.board = next_board
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def new_board(self, height, width, p_alive):
        """
        This function creates a Game of Life game board.

        Parameters
        ----------
            height : integer
                the height of the board
            width : integer
                the width of the board
            p_alive : float
                the chance that a cell is set to 'alive', must be between [0, 1]
                
        """
        dead, alive = 0, 1
        p_dead = 1 - p_alive # We know that if a cell is not alive, it must be dead
        self.board = np.random.choice(
            [self.DEAD, self.ALIVE], p=[p_dead, p_alive], size=(height, width)
        )

    def count_living_neighbors(self, r, c):
        """
        Counts the number of living neighbors around an array cell.

        Parameters
        ----------
            board : 2d array
            r : int
                row index
            c : int
                column index

        Returns
        ----------
            int
                number of living neighbors

        """
        num_rows, num_cols = self.board.shape

        u_ = self.board[(r-1) % num_rows, c % num_cols]
        d_ = self.board[(r+1) % num_rows, c % num_cols]
        l_ = self.board[r % num_rows, (c-1) % num_cols]
        r_ = self.board[r % num_rows, (c+1) % num_cols]
        ul = self.board[(r-1) % num_rows, (c-1) % num_cols]
        ur = self.board[(r-1) % num_rows, (c+1) % num_cols]
        dl = self.board[(r+1) % num_rows, (c-1) % num_cols]
        dr = self.board[(r+1) % num_rows, (c+1) % num_cols]

        return (u_ + d_ + l_ + r_ + ul + ur + dl + dr)

    def compute_next_state(self, current_state, num_living_neighbors):
        """
        Computes the state of a cell in the next generation of a Game of Life.

        Parameters
        ----------
            current_state : int
            num_living_neighbors : int

        Returns
        ----------
            next_state : int

        """
        next_state = self.DEAD

        if (num_living_neighbors < 2) and (current_state == self.ALIVE):
            # Dies by under-population
            next_state = self.DEAD
        elif ( 2 <= num_living_neighbors <= 3) and (current_state == self.ALIVE):
            # Survives on to the next generation
            next_state = self.ALIVE
        elif (num_living_neighbors > 3) and (current_state == self.ALIVE):
            # Dies by over-population
            next_state = self.DEAD
        elif (num_living_neighbors == 3) and (current_state == self.DEAD):
            # Live cell is birthed 
            next_state = self.ALIVE

        return next_state
    
    def restart(self):
        """Restart the Game of Life simulation with a new board"""
        pass

In [10]:
simulation = GameOfLife()
simulation.start(height=10, width=10)
print('Starting Board:')
print(simulation.board)
print('Next Board:')
simulation.step()
print(simulation.board)

Starting Board:
[[0 1 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0]
 [0 0 1 1 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 1]
 [1 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]
Next Board:
[[0 1 1 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 0 1 0 0]
 [0 0 1 0 0 1 0 1 0 0]
 [0 0 0 0 1 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0]
 [0 1 0 1 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]]


And finally let's add the ability to query the board to see if it is empty and to restart, if it is.

In [11]:
class GameOfLife:
    """Conway's Game of Life"""
    DEAD, ALIVE = 0, 1
    def __init__(self):
        """Initialize a class instance"""
        self.board = None
        
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        return (self.board == 0).all()
    
    def restart(self, height, width, p_alive):
        """Restart the Game of Life simulation with a new board"""
        self.board = self.new_board(height, width, p_alive)
    
    def start(self, height, width, p_alive=.3):
        """Start a new simulation."""
        self.new_board(height, width, p_alive)
    
    def step(self):
        """Step the simulation forward a generation."""
        # Copy the current board for the next generation
        next_board = self.board.copy()
        # Loop over all of the cells in the current board
        num_rows, num_cols = self.board.shape
        for r in range(num_rows):
            for c in range(num_cols):
                # Fetch the current state of this cell
                current_state = self.board[r, c]
                # Count the number of living neighbors
                num_living_neighbors = self.count_living_neighbors(r, c)
                # Figure out if this cell will be alive or dead in the next board
                next_state = self.compute_next_state(current_state, num_living_neighbors)
    #             next_state = 1
                # Set the state of this cell in the next board
                next_board[r, c] = next_state  

        self.board = next_board
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def new_board(self, height, width, p_alive):
        """
        This function creates a Game of Life game board.

        Parameters
        ----------
            height : integer
                the height of the board
            width : integer
                the width of the board
            p_alive : float
                the chance that a cell is set to 'alive', must be between [0, 1]
                
        """
        dead, alive = 0, 1
        p_dead = 1 - p_alive # We know that if a cell is not alive, it must be dead
        self.board = np.random.choice(
            [self.DEAD, self.ALIVE], p=[p_dead, p_alive], size=(height, width)
        )

    def count_living_neighbors(self, r, c):
        """
        Counts the number of living neighbors around an array cell.

        Parameters
        ----------
            board : 2d array
            r : int
                row index
            c : int
                column index

        Returns
        ----------
            int
                number of living neighbors

        """
        num_rows, num_cols = self.board.shape

        u_ = self.board[(r-1) % num_rows, c % num_cols]
        d_ = self.board[(r+1) % num_rows, c % num_cols]
        l_ = self.board[r % num_rows, (c-1) % num_cols]
        r_ = self.board[r % num_rows, (c+1) % num_cols]
        ul = self.board[(r-1) % num_rows, (c-1) % num_cols]
        ur = self.board[(r-1) % num_rows, (c+1) % num_cols]
        dl = self.board[(r+1) % num_rows, (c-1) % num_cols]
        dr = self.board[(r+1) % num_rows, (c+1) % num_cols]

        return (u_ + d_ + l_ + r_ + ul + ur + dl + dr)

    def compute_next_state(self, current_state, num_living_neighbors):
        """
        Computes the state of a cell in the next generation of a Game of Life.

        Parameters
        ----------
            current_state : int
            num_living_neighbors : int

        Returns
        ----------
            next_state : int

        """
        next_state = self.DEAD

        if (num_living_neighbors < 2) and (current_state == self.ALIVE):
            # Dies by under-population
            next_state = self.DEAD
        elif ( 2 <= num_living_neighbors <= 3) and (current_state == self.ALIVE):
            # Survives on to the next generation
            next_state = self.ALIVE
        elif (num_living_neighbors > 3) and (current_state == self.ALIVE):
            # Dies by over-population
            next_state = self.DEAD
        elif (num_living_neighbors == 3) and (current_state == self.DEAD):
            # Live cell is birthed 
            next_state = self.ALIVE

        return next_state

In [12]:
simulation = GameOfLife()
simulation.start(height=10, width=10)
while True:
    simulation.step()
    if simulation.is_empty():
        simulation.restart(height=10, width=10)

KeyboardInterrupt: 