# Object Oriented Programming
---

In the last lesson, we wrote code in a 'functional' style. It's called the 'functional' style of programming because we wrote separate, isolated functions and chained them together to accomplish our goal. This is a perfectly valid way of writing code, and has pros and cons just like any other style of programming. 

What we'll explore next is a style of programming called Object Oriented Programming (OOP). OOP is a programming paradigm that gives us the ability to think more abstractly and structure our code as if it were a real-world object. 

Instead of passing an array that represents a Game of Life board between functions, we'll create a Game of Life 'object' that 'owns' a simulation board and can do things with it. The difference may not be super clear right now but it will hopefully come more into focus when we start to write some code. 

This style of programming also has pros and cons which we won't get into those here. People spend years and years getting familiar with different programming paradigms, and I think that the best way to learn about them is through experience. Don't sweat it too much now --- try writing code, and try writing code different ways. You'll figure out what works and what doesn't.

## Administrivia

Let's import NumPy again.

In [13]:
import numpy as np

## A Quick Introduction to Classes

We can use classes to store attributes of objects. Let's imagine a world where there every square is the same size:

In [18]:
# A super simple class.
class Square:
    width = 10
    
Square.width

10

We can also use classes as a template to create *similar* objects. A world where every square is the same size is boring, let's create a square object that can take on different sizes.

If we add a method (functions under classes are referred to as 'methods') to the Square class called `__init__()` we can create 'instances' of Squares with different attributes.

* NOTE: `__init__()` is not an arbitrary name, it is defined by Python.

In [16]:
# A bit more complicated
class Square:
    def __init__(self, width):
        self.width = width
        
square1 = Square(10)
square2 = Square(20)

print('The width of Square 1 is:', square1.width)
print('The width of Square 2 is:', square2.width)

The width of Square 1 is: 10
The width of Square 2 is: 20


Notice how the `__init__()` method takes two parameters? The second one, `width`, is intuitive but what about the first one, `self`? `self` is a reference to a specific instance of a class (namely the instance that we're working with). All of the methods that you write under a class will recieve `self` as their first argument, and this provides you with the ability to assign something like a `width` to *this instance's* width.

Here, let's write another method for the Square class:

In [17]:
# A bit more complicated
class Square:
    def __init__(self, width):
        self.width = width
        
    def double_width(self):
        self.width = self.width * 2
        
square = Square(10)
print('The width of the square is:', square.width)
square.double_width()
print('The width of square is:', square.width)

The width of the square is: 10
The width of square is: 20


Note how the new method, `double_width()`, takes `self` as an argument. If it didn't do this, we would have no way to access the width that we passed in when we first created the Square. 

## Game of Life Class

Let's try our hand at writing a Game of Life class. Most of what we'll do here is copy over functions that we wrote in the last lesson, so you may want to open that notebook next to this one.

We should start by thinking about the properties that our Game of Life object should have as well as the sorts of actions it should be able to perform.

* It should be able to start a simulation with a new board
* It should be able to step forward through generations
* We may want to start a new simulation if all of the cells in the board are dead, so we should write a function to query the board to see if all the cells are dead

In [1]:
# Skeleton Class
class GameOfLife:
    """Conway's Game of Life"""
    def __init__(self):
        """Initialize a class instance"""
        pass

    def start(self):
        """Start a new simulation."""
        pass
    
    def step(self):
        """Step the simulation forward a generation."""
        pass
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def restart(self):
        """Restart the Game of Life simulation with a new board"""
        pass

Now let's start filling this class in.

We'll start with our initialization method. We don't have a simulation running yet, but we want a 'board' attribute to be accessible to the other functions in the class, so we'll go ahead and add an empty board.

In [2]:
class GameOfLife:
    """Conway's Game of Life"""
    def __init__(self):
        """Initialize a class instance"""
        self.board = None

    def start(self):
        """Start a new simulation."""
        pass
    
    def step(self):
        """Step the simulation forward a generation."""
        pass
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def restart(self):
        """Restart the Game of Life simulation with a new board"""
        pass

In [3]:
simulation = GameOfLife()
print(simulation.board)

None


Next we'll write the start method. This should create a new game board of a given size. We'll rip off the `create_board` function that we wrote earlier, rename it as `new_board`, which makes more sense in this context, and call that function under our class's start method.

In [4]:
class GameOfLife:
    DEAD, ALIVE = 0, 1 # These are Class variables
    """Conway's Game of Life"""
    def __init__(self):
        """Initialize a class instance"""
        self.board = None

    def start(self, height, width, p_alive=.3):
        """Start a new simulation."""
        self.new_board(height, width, p_alive)
    
    def step(self):
        """Step the simulation forward a generation."""
        pass
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def new_board(self, height, width, p_alive):
        """
        This function creates a Game of Life game board.

        Parameters
        ----------
            height : integer
                the height of the board
            width : integer
                the width of the board
            p_alive : float
                the chance that a cell is set to 'alive', must be between [0, 1]
                
        """
        p_dead = 1 - p_alive # We know that if a cell is not alive, it must be dead
        self.board = np.random.choice(
            [self.DEAD, self.ALIVE], p=[p_dead, p_alive], size=(height, width)
        )
    
    def restart(self):
        """Restart the Game of Life simulation with a new board"""
        pass

In [7]:
simulation = GameOfLife()
simulation.start(height=10, width=10)
simulation.board

array([[0, 1, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0]])

Next, let's add in the functionality to step to the next generation.

In [9]:
class GameOfLife:
    """Conway's Game of Life"""
    DEAD, ALIVE = 0, 1
    def __init__(self):
        """Initialize a class instance"""
        self.board = None

    def start(self, height, width, p_alive=.3):
        """Start a new simulation."""
        self.new_board(height, width, p_alive)
    
    def step(self):
        """Step the simulation forward a generation."""
        # Copy the current board for the next generation
        next_board = self.board.copy()
        # Loop over all of the cells in the current board
        num_rows, num_cols = self.board.shape
        for r in range(num_rows):
            for c in range(num_cols):
                # Fetch the current state of this cell
                current_state = self.board[r, c]
                # Count the number of living neighbors
                num_living_neighbors = self.count_living_neighbors(r, c)
                # Figure out if this cell will be alive or dead in the next board
                next_state = self.compute_next_state(current_state, num_living_neighbors)
    #             next_state = 1
                # Set the state of this cell in the next board
                next_board[r, c] = next_state  

        self.board = next_board
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def new_board(self, height, width, p_alive):
        """
        This function creates a Game of Life game board.

        Parameters
        ----------
            height : integer
                the height of the board
            width : integer
                the width of the board
            p_alive : float
                the chance that a cell is set to 'alive', must be between [0, 1]
                
        """
        dead, alive = 0, 1
        p_dead = 1 - p_alive # We know that if a cell is not alive, it must be dead
        self.board = np.random.choice(
            [self.DEAD, self.ALIVE], p=[p_dead, p_alive], size=(height, width)
        )

    def count_living_neighbors(self, r, c):
        """
        Counts the number of living neighbors around an array cell.

        Parameters
        ----------
            board : 2d array
            r : int
                row index
            c : int
                column index

        Returns
        ----------
            int
                number of living neighbors

        """
        num_rows, num_cols = self.board.shape

        u_ = self.board[(r-1) % num_rows, c % num_cols]
        d_ = self.board[(r+1) % num_rows, c % num_cols]
        l_ = self.board[r % num_rows, (c-1) % num_cols]
        r_ = self.board[r % num_rows, (c+1) % num_cols]
        ul = self.board[(r-1) % num_rows, (c-1) % num_cols]
        ur = self.board[(r-1) % num_rows, (c+1) % num_cols]
        dl = self.board[(r+1) % num_rows, (c-1) % num_cols]
        dr = self.board[(r+1) % num_rows, (c+1) % num_cols]

        return (u_ + d_ + l_ + r_ + ul + ur + dl + dr)

    def compute_next_state(self, current_state, num_living_neighbors):
        """
        Computes the state of a cell in the next generation of a Game of Life.

        Parameters
        ----------
            current_state : int
            num_living_neighbors : int

        Returns
        ----------
            next_state : int

        """
        next_state = self.DEAD

        if (num_living_neighbors < 2) and (current_state == self.ALIVE):
            # Dies by under-population
            next_state = self.DEAD
        elif ( 2 <= num_living_neighbors <= 3) and (current_state == self.ALIVE):
            # Survives on to the next generation
            next_state = self.ALIVE
        elif (num_living_neighbors > 3) and (current_state == self.ALIVE):
            # Dies by over-population
            next_state = self.DEAD
        elif (num_living_neighbors == 3) and (current_state == self.DEAD):
            # Live cell is birthed 
            next_state = self.ALIVE

        return next_state
    
    def restart(self):
        """Restart the Game of Life simulation with a new board"""
        pass

In [10]:
simulation = GameOfLife()
simulation.start(height=10, width=10)
print('Starting Board:')
print(simulation.board)
print('Next Board:')
simulation.step()
print(simulation.board)

Starting Board:
[[0 1 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0]
 [0 0 1 1 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 1]
 [1 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]
Next Board:
[[0 1 1 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 0 1 0 0]
 [0 0 1 0 0 1 0 1 0 0]
 [0 0 0 0 1 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0]
 [0 1 0 1 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]]


And finally let's add the ability to query the board to see if it is empty and to restart, if it is.

In [11]:
class GameOfLife:
    """Conway's Game of Life"""
    DEAD, ALIVE = 0, 1
    def __init__(self):
        """Initialize a class instance"""
        self.board = None
        
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        return (self.board == 0).all()
    
    def restart(self, height, width, p_alive):
        """Restart the Game of Life simulation with a new board"""
        self.board = self.new_board(height, width, p_alive)
    
    def start(self, height, width, p_alive=.3):
        """Start a new simulation."""
        self.new_board(height, width, p_alive)
    
    def step(self):
        """Step the simulation forward a generation."""
        # Copy the current board for the next generation
        next_board = self.board.copy()
        # Loop over all of the cells in the current board
        num_rows, num_cols = self.board.shape
        for r in range(num_rows):
            for c in range(num_cols):
                # Fetch the current state of this cell
                current_state = self.board[r, c]
                # Count the number of living neighbors
                num_living_neighbors = self.count_living_neighbors(r, c)
                # Figure out if this cell will be alive or dead in the next board
                next_state = self.compute_next_state(current_state, num_living_neighbors)
    #             next_state = 1
                # Set the state of this cell in the next board
                next_board[r, c] = next_state  

        self.board = next_board
    
    def is_empty(self):
        """Check to see if the Game of Life board is empty"""
        pass
    
    def new_board(self, height, width, p_alive):
        """
        This function creates a Game of Life game board.

        Parameters
        ----------
            height : integer
                the height of the board
            width : integer
                the width of the board
            p_alive : float
                the chance that a cell is set to 'alive', must be between [0, 1]
                
        """
        dead, alive = 0, 1
        p_dead = 1 - p_alive # We know that if a cell is not alive, it must be dead
        self.board = np.random.choice(
            [self.DEAD, self.ALIVE], p=[p_dead, p_alive], size=(height, width)
        )

    def count_living_neighbors(self, r, c):
        """
        Counts the number of living neighbors around an array cell.

        Parameters
        ----------
            board : 2d array
            r : int
                row index
            c : int
                column index

        Returns
        ----------
            int
                number of living neighbors

        """
        num_rows, num_cols = self.board.shape

        u_ = self.board[(r-1) % num_rows, c % num_cols]
        d_ = self.board[(r+1) % num_rows, c % num_cols]
        l_ = self.board[r % num_rows, (c-1) % num_cols]
        r_ = self.board[r % num_rows, (c+1) % num_cols]
        ul = self.board[(r-1) % num_rows, (c-1) % num_cols]
        ur = self.board[(r-1) % num_rows, (c+1) % num_cols]
        dl = self.board[(r+1) % num_rows, (c-1) % num_cols]
        dr = self.board[(r+1) % num_rows, (c+1) % num_cols]

        return (u_ + d_ + l_ + r_ + ul + ur + dl + dr)

    def compute_next_state(self, current_state, num_living_neighbors):
        """
        Computes the state of a cell in the next generation of a Game of Life.

        Parameters
        ----------
            current_state : int
            num_living_neighbors : int

        Returns
        ----------
            next_state : int

        """
        next_state = self.DEAD

        if (num_living_neighbors < 2) and (current_state == self.ALIVE):
            # Dies by under-population
            next_state = self.DEAD
        elif ( 2 <= num_living_neighbors <= 3) and (current_state == self.ALIVE):
            # Survives on to the next generation
            next_state = self.ALIVE
        elif (num_living_neighbors > 3) and (current_state == self.ALIVE):
            # Dies by over-population
            next_state = self.DEAD
        elif (num_living_neighbors == 3) and (current_state == self.DEAD):
            # Live cell is birthed 
            next_state = self.ALIVE

        return next_state

In [20]:
simulation = GameOfLife()
simulation.start(height=10, width=10)
for i in range(10):
    print(simulation.board)
    simulation.step()
    if simulation.is_empty():
        simulation.restart(height=10, width=10)

[[0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 1 1 0 1 0]
 [0 1 1 0 1 0 1 0 0 1]
 [0 1 1 1 1 0 0 1 0 0]]
[[0 1 0 1 0 0 1 1 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 1 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 1 0 0 0 1]
 [0 0 1 1 0 1 1 1 0 0]
 [0 0 0 0 1 0 1 0 1 1]
 [0 0 0 0 1 1 0 0 0 0]]
[[1 1 1 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 1 1 1 1 0 0 0 1]
 [1 1 1 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 1 0]]
[[0 0 0 0 1 0 1 0 1 0]
 [0 0 1 1 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 1 1]
 [0 1 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 1 1 1]
 [0 1 1 1 1 0 0 1 0 1]]
[[0 1 0 0 1 0 1 0 1 1]
 [0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 0 1 0 0 0]
 [1 0 0