# An Introduction to Lists and Arrays
---

## Python Lists

In Python, we can use a data structure called a `list`, to represent an ordered collection of things. A Python list is a sequence of objects, separated by commas, inside of square brackets (`[]`). Here's a simple list that stores the numbers 1-5:

In [3]:
my_list = [1, 2, 3, 4, 5]

print(my_list)

[1, 2, 3, 4, 5]


We can create empty lists and add new things to them:

In [10]:
my_list = []
my_list.append(1)
my_list.append(2)
my_list.append(3)
my_list.append(4)
my_list.append(5)

print(my_list)

[1, 2, 3, 4, 5]


And we can also pull elements out of lists:

In [16]:
my_list = [1, 2, 3, 4, 5]
first_element = my_list[0]

print(first_element)

1


Let's spend a second going over this bit of code from the cell above:

    first_element = my_list[0]

I'm defining a new variable, `first_element`, and setting it equal to `my_list[0]`. `my_list` is a list that we created, and the `[0]` is the syntax we use to access an element of a sequence. 

Python is a *zero-based* programming language. This means that when we're counting the order of elements in a sequence, the first element is the 0-th element, the second one is the 1-st element, etc... This may be confusing at first, but has a lot of nice properties that you'll come to appreciate later. In this example, we get the first element of the list, the number 1, by selecting the 0-th element. 

How would we get the number 3 out of `my_list`?

In [17]:
my_list[2]

3

### Advanced Indexing

In [60]:
# The : is a special character that represents the whole list
my_list[:]

[1, 2, 3, 4, 5]

In [68]:
# We can also use negative indices. Counting backwards from index 0,
# they wrap around the back of the list.
my_list[-1]

5

In [65]:
my_list[-4]

2

In [69]:
# We can select ranges
my_list[1:3]

[2, 3]

In [71]:
# And we can specify a step value. 
# This gets every other entry in the array.
my_list[::2]

[1, 3, 5]

In [72]:
# And this is a tricky way to reverse a list
my_list[::-1]

[5, 4, 3, 2, 1]

## NumPy Arrays

`NumPy` is an external Python package self-described as 

> **the** fundamental package for scientific computing with Python. [emphasis added]

We traditionally import `NumPy` into Python as follows:

In [21]:
import numpy as np

Among other things, `NumPy` provides an easy and efficient way of creating and manipulating multidimensional arrays. Python `lists` can be multi-dimensional, but it is usually much easier to work with multi-dimensional lists using `NumPy`. For example to create a 3x3, 2D list filled with the number 1 in Python:

In [26]:
two_dimensional_list = []
for i in range(3):
    row = []
    for j in range(3):
        row.append(1)
    two_dimensional_list.append(row)

print(two_dimensional_list)

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]


And to do the same with `NumPy`:

In [27]:
two_dimensional_array = np.ones((3,3))

print(two_dimensional_array)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


### Indexing with NumPy

Indexing and selecting operationos on `NumPy` arrays are similar to indexing and selecting operations on Python lists, with a few extra features.

In [50]:
# Let's create an array to do some indexing operations on:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
# First row:
a[0]

array([0, 1, 2])

In [53]:
# First column:
a[:, 0]

array([0, 3, 6])

In [56]:
# Upper-left element
a[0, 0]

0

In [57]:
# Lower-right element
a[2, 2]

8

In [58]:
# Ignore the first row and first column
a[1:, 1:]

array([[4, 5],
       [7, 8]])

In [59]:
# Every other element
a[::2, ::2]

array([[0, 2],
       [6, 8]])

## More Resources

* https://docs.python.org/3/tutorial/introduction.html#lists
* https://docs.scipy.org/doc/numpy/user/quickstart.html